### ISSUE TITLE
Multiple ShaderPasses per Plane

### ISSUE THREAD

**Issue by GeorgeHastings** [martinlaxenaire/curtainsjs#102]
Hey @[martinlaxenaire](https://github.com/martinlaxenaire),

I'm struggling to apply an arbitrary amount of ShaderPasses to a Plane with RenderTargets. It appears that when I add a second ShaderPass to a RenderTarget, it applies its fragmentShader to the original canvas texture, however, I am trying to make the "effects" chain together. 

Maybe this should be done with a PingPongShader?

Here's a demo, you need to move your mouse in the canvas to render it. I'm trying to be able to individually manipulate these shapes (position, size, one or many shaderpasses, etc). You'll see the half opacity shader and the wavy shader just render overtop of each-other rather than in succession. 

https://codepen.io/georgehastings/pen/RwxrrRa?editors=0010

Any help would be greatly appreciated!

**edit**: I know this could be done by using one shader and uniforms + mix() however for my purposes there could be dozens of individual shaders many of which have for loops, if/else, and lots of texture sampling. I have a hard time seeing how that would be manageable/performant in one fragmentShader (esp. b/c I want to control the order in which operations are applied) but maybe?

**Comment by GeorgeHastings** [comment]
So I've been spending a lot of time with this, and it seems that one unexpected factor of the result I'm seeing is from using the word `plane` as the id for my html wrapper element. Nothing shows up if I use `plane_html` for example.

**Comment by martinlaxenaire** [comment]
Hi @GeorgeHastings,

I'm having a hard time understanding what you are trying to do.

1) a `Plane` can only have one `RenderTarget`
2) a `RenderTarget` can only be used by one `ShaderPass`
3) Always try to do the maximum possible in one pass / shader instead of using cumulative passes (which mean more draw calls)
4) If you do want to use cumulative passes anyway, just don't pass any `RenderTarget` to your `ShaderPass`. Each `ShaderPass` will use the previous output as input.

As for your second comment, you should pass an HTML element to the `Plane` constructor, like that:

```javascript
item.plane = new Plane(curtains, document.getElementById("plane"), {
  vertexShader: vs,
  fragmentShader: fs,
});
```

Cheers,

**Comment by GeorgeHastings** [comment]
No worries, 1. and 2. answer my question. I have n shaderpasses applying to the scene fine currently but I'm trying to make that possible on an individual plane level (e.g. blur one box, not the others). I think a big complex shader could do it after some light exploration. 

RE: the id, `plane` (without document.getElementById) will reference the HTML element if theres one in the DOM with that id. Will show up as such in the console at least FWIW.

 Will close. Thank you for taking a look!
