### ISSUE TITLE
[Performance Questions] Ability to generate a single program as opposed to one per plane.

### ISSUE THREAD

**Issue by 23d1** [martinlaxenaire/curtainsjs#20]
Would it make sense to generate just one program that updates as things come into view, rather than generating a program per plane where possible (one shader instance and so forth)? Would that help performance? Is there any value in using off-screen canvas to help improve performance?

**Comment by martinlaxenaire** [comment]
Hi @23d1,

thanks a lot for these suggestions.

I've been thinking of it since I first saw your issue and found some time to make some tests these last couple days.

Passing the webgl context to an offscreen canvas whenever possible was fairly easy to implement. Altho I've not seen any significative performance improvement, it might still be a good idea so I'll be adding in the next release.

As for managing shared webgl programs among planes that use the same shaders, the first tests show a real increase in performance when adding a bunch of planes (mostly by avoiding unnecessary shaders compilations).

I still need to runs some more tests to be sure everything's working fine but it will most probably be featured in the next release as well!

Thanks again for those suggestions, I really appreciate!

Cheers,

**Comment by 23d1** [comment]
Hey @martinlaxenaire,

That's awesome. I have a project where the amount of planes on some pages would be quite a lot, so it'll definitely help the performance for that specific project.

Any rough ETA on when you might push a new release? I can't wait to try it out. :)

Cheers!

**Comment by martinlaxenaire** [comment]
Hey @23d1,

I've just released a new version (4.1.0) including the shared programs improvement, you might want to try it.

I've not included the offscreen canvas part as I noticed this introduced a slight noticeable delay, especially while scrolling (just spent 3 hours trying to debug that before switching offscreen canvas off and noticing this was the cause of the issue).

Cheers,

**Comment by 23d1** [comment]
Awesome, will check it out!

Might be worth introducing as an option? Not sure how much it adds to the overall codebase though.
