### ISSUE TITLE
 Canvas text isn't updated

### ISSUE THREAD

**Issue by AlainBarrios** [martinlaxenaire/curtainsjs#21]
I am trying to update the text on the canvas, but it is not updated, by the way, the plane.textures[0].needUpdate() method does not exist in the texture 

this is the pen
https://codepen.io/AlainBarrios/pen/jOOKWNX?editors=0010

**Comment by martinlaxenaire** [comment]
Hi @AlainBarrios,

Is your pen still broken? Looks OK to me.

Cheers,

**Comment by AlainBarrios** [comment]
> Hi @AlainBarrios,
> 
> Is your pen still broken? Looks OK to me. Or did I miss something?
> 
> Cheers,

The text does not update its size correctly, it deforms and loses quality.

it's a clip
https://gyazo.com/399001995f739258e5f7e5bb0419b31f

**Comment by martinlaxenaire** [comment]
Hi @AlainBarrios,

here's a fixed forked version of your pen: https://codepen.io/martinlaxenaire/pen/VwwOPYZ

The texture matrix calcs seem however a bit buggy in this case. I'll look into it, meanwhile if you're using a canvas texture, just don't use the texture matrix in your vertex shader texture coords calcs.

Cheers,

**Comment by AlainBarrios** [comment]
Why in this case I should not use the texture matrix?

**Comment by martinlaxenaire** [comment]
Hey @AlainBarrios,

the texture matrix is used to properly map your source (image, video or canvas) onto the plane. It is useful to achieve a correct cropping/scaling when your source and your plane does not have the same dimensions (check this article if you want to read more about texture matrices: https://webglfundamentals.org/webgl/lessons/webgl-2d-drawimage.html ).

When dealing with canvas texture however, we usually set the canvas to be the same size as our plane, therefore not really needing the use of the texture matrix.

In this case, the texture matrix calcs on resize are wrong because they are done before the canvas has actually been resized (they are based on the new plane sizes and the old canvas sizes).
I think I will add a texture resize() method that you could call after any source has been resized to update the texture matrix with the new sizes values.

I hope I'm making myself clear!

Cheers,

**Comment by martinlaxenaire** [comment]
Fixed with v4.2 and texture resize() method (see: https://www.curtainsjs.com/examples/multiple-planes-canvas-text/ )
