### ISSUE TITLE
Implementing a morphing page transition

### ISSUE THREAD

**Issue by ajayns** [martinlaxenaire/curtainsjs#32]
Hey Martin! 
Enjoying working with the library so far, great work. This is a query for approach rather than an issue.

I'm attempting to implement a morphing page transition: much like the ajax navigation example but on both the pages, the same image is present and the page transition (instead of fade from your example) morphs between the sizes and positions of the image in different pages.

For the process of morphing, I move the image to `position: fixed` and modify values of width, height, top, left. So curtains seem to work fine when I remove planes right before the transition and add planes right after it is over but if I want to keep the plane during the course of the transition, it doesn't seem to work. 
Since the position changes, I figured during the course of the transition I could call `plane.updatePosition` on render but that only seems to cause the plane itself to disappear during the transition. Is there any condition that position tracking only works for elements position relative or static?

Thanks,
Ajay

**Comment by martinlaxenaire** [comment]
Hi @ajayns!

I think the way you're doing your transition is not the most optimal: as I understand you're animating the HTML element size and position and call the `updatePosition()` to sync your plane.
That means you'll trigger a repaint at each frame of your animation which is not really good in terms of performance.

For that kind of animations, I usually tween the scale and position of the plane:
- Get your plane current size and position with `plane.getBoundingRect()` (and eventually your canvas/window size with `curtains.getBoundingRect()`)
- Calculate your plane final scale and position based on the previous values and the final plane's size and position
- Set your plane transform origin to [0, 0] (top left corner) to make your calculations easier: `plane.setTransformOrigin(0, 0);`
- Start your tween and update your position and scale in the update callback with `plane.setScale()` and `plane.setRelativePosition()`

Since you'd want to keep that plane alive, just don't remove it but instead reset it with the new according HTML element once your new content has been appended:
`const newHTMLEl = document.getElementById("my-element"); // you could use querySelector()
 plane.resetPlane(newHTMLEl );`

That should do the trick (at least that's how I'm doing it myself).

Also, planes do work well with fixed elements. In your case it might be because the actual HTML element isn't in your viewport or something like that?

Cheers,

**Comment by ajayns** [comment]
Thank you for the fast response.

I was aware it isn't the best performance-wise, I was mostly prototyping and experimenting on how to achieve the effects while using this library. Your approach seems solid though, so I'll try what you've mentioned and get back to you soon. 
Also, the resetPlane was probably what I was looking for, I was unaware of that. Good job on covering a wide range of options in your API!

Thanks again

**Comment by ajayns** [comment]
This works perfectly, thanks again Martin. I'm closing the issue.
