### ISSUE TITLE
Gray border when creating effects that change the edge of the image

### ISSUE THREAD

**Issue by VadymPogorelov** [martinlaxenaire/curtainsjs#44]
When creating effects that change the edge of an image (for example, waves), a gray border appears along the perimeter of the image in browsers running under Windows 10. When working in Windows 7, there is no such border. This effect [https://prnt.sc/sx1jt1](https://prnt.sc/sx1jt1), [https://prnt.sc/sx2nw3](https://prnt.sc/sx2nw3) is visible even on your demos from the page [https://www.curtainsjs.com/](https://www.curtainsjs.com/)
Can something be done about it?
P.S. The border does not appear on effects that do not affect the edge of the image (tint, replace image, etc.).

**Comment by martinlaxenaire** [comment]
Hi @VadymPogorelov,

this is likely due to WebGL alpha compositing.
Setting the `premultipliedAlpha` option to `true` on curtains init ([https://www.curtainsjs.com/curtains-class.html#curtains-init-parameters](https://www.curtainsjs.com/curtains-class.html#curtains-init-parameters)) should solve this issue at the moment, but I should also definitely find a way to add more control over each texture premultiplied alpha parameter.

You're right tho and I'll update the library website with this setting on next release. Thanks for pointing that out!

**Comment by VadymPogorelov** [comment]
Thank you very much for your quick response and also thank you very much for your work - your script works great
