### ISSUE TITLE
RenderTarget does not render

### ISSUE THREAD

**Issue by AlainBarrios** [martinlaxenaire/curtainsjs#49]
Hi Martin. 
Could you say what problem I have, since the rendertarget does not load?
it's a trace with the mouse

https://codepen.io/AlainBarrios/pen/WNvoaXx

**Comment by martinlaxenaire** [comment]
Hi @AlainBarrios,

from what I cen tell by debugging your WebGL scene with [spector.js](https://spector.babylonjs.com/), there is actually a trail drawn inside your render targets texture.
Therefore this is not a bug and my guess is your issue is likely coming from your javascript and/or your shaders code.

Cheers,
