### ISSUE TITLE
Ping-Pong Plane with shaderpass order of creation problem

### ISSUE THREAD

**Issue by andrewleek-droplab** [martinlaxenaire/curtainsjs#65]
Here I have two fiddles to illustrate the issue I am encountering:

This first one is working as expected ...
https://jsfiddle.net/AndrewLeek/hm84se2j/21/

This second one is broken and results in no flowmap input/interaction ...
https://jsfiddle.net/AndrewLeek/hm84se2j/22/

The only difference is that in the second fiddle, I am creating the ping-pong-plane after creating the four image planes.

Any light you can shed on this would be greatly appreciated as I was pulling my hair out trying to figure out why it was not working...

Cheers,

**Comment by martinlaxenaire** [comment]
Hey @andrewleek-droplab,

First, there were actually a couple minor issues that should now be fixed in v7.1.4 - c049756bfc1f105d098000b9d30c849e046dee99

So, for this to work you'll need to move your four planes to the front so they'll be drawn after the ping pong plane. See line 307 of this fiddle: https://jsfiddle.net/v3w6zsbx/

The render order does matter here, because WebGL needs to bind the ping pong plane frame buffer and draw it **before** binding the shader pass frame buffer and draw the remaining of the scene.
At the moment, the library draws the planes in the order of their creation. So in your scene, the ping pong plane frame buffer was bound and drawn after the content of the shader pass was being drawn, hence the issue.

A possible enhancement here could be to update the [Scene class](https://github.com/martinlaxenaire/curtainsjs/blob/master/src/core/Scene.js) so it always draw PingPongPlane class content before anything else. I'll add this to my TODO list.

Cheers,
